apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: {{ .Values.slave.replicaCount }}
  selector:
    matchLabels:
      role: slave
  template:
    metadata:
      labels:
        role: slave
    spec:
      containers:
      - name: redis-slave
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: {{ .Values.slave.resources.requests.cpu }}
            memory: {{ .Values.slave.resources.requests.memory }}
          limits:
            cpu: {{ .Values.slave.resources.limits.cpu }}
            memory: {{ .Values.slave.resources.limits.memory }}
        command: [ "redis-server", "--slaveof", "redis-master", "6379" ]