apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      role: master
  template:
    metadata:
      labels:
        role: master
    spec:
      containers:
        - name: redis-master
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          ports:
            - containerPort: 80
