apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      role: master
  template:
    metadata:
      labels:
        role: master
    spec:
      containers:
        - name: redis-master
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: {{ .Values.master.resources.requests.cpu }}
              memory: {{ .Values.master.resources.requests.memory }}
            limits:
              cpu: {{ .Values.master.resources.limits.cpu }}
              memory: {{ .Values.master.resources.limits.memory }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: {{ .Values.master.storage }}